// It is an autogenerated file and will be rewritten on the next save.



// #region Items

const item = {
	usual: 'ag:ww',
	qwfw: {
		assgw: 'gwge:ggwe[e:fw=0]'
	}
}

// #endregion



// #region Tags

const tag = {
	shaft: '#sugoma:shaft'
}

// #endregion



// #region Fluids

const fluid = {
	water: 'minecraft:water'
}

// #endregion



