using System.Text;
using EasyKJSCrafter.Scenes.UIs.DeclarationTabUI;
using Godot;
using static EasyKJSCrafter.Common.Logger.Logger;

namespace EasyKJSCrafter.Scenes.UIs.DeclarationsRedactor
{
	public partial class DeclarationsRedactor : Control
	{
		TabContainer DeclarationContainer => GetNode<TabContainer>("PanelContainer/VBoxContainer/HBoxContainer/DeclarationTabContainer");
		HBoxContainer SaveContainer => GetNode<HBoxContainer>("PanelContainer/VBoxContainer/SaveHBoxContainer");
		FileDialog WhereToSaveDialog => GetNode<FileDialog>("WhereToSaveDialog");

		DeclarationTab ItemsTab => DeclarationContainer.GetNode<DeclarationTab>("ItemsTab");
		DeclarationTab TagsTab => DeclarationContainer.GetNode<DeclarationTab>("TagsTab");
		DeclarationTab FluidsTab => DeclarationContainer.GetNode<DeclarationTab>("FluidsTab");

		Label SaveInfoLabel => SaveContainer.GetNode<Label>("SaveInfoLabel");
		
		void OnBackButton_Pressed()
		{
			Manager.Main.UIHandler.ChangeTo(Manager.LoadedUIScenes.MainMenu);
		}

		void OnSaveCollectionsButton_Pressed()
		{
			StringBuilder errors = new("При сохранении ");
			int l = errors.Length;
			bool itemsSaved = ItemsTab.SaveCollection();
			bool tagsSaved = TagsTab.SaveCollection();
			bool fluidsSaved = FluidsTab.SaveCollection();
			if (!itemsSaved)
			{
				if (errors.Length > l)
					errors.Append(", ");
				errors.Append("Предметов");
			}
			if (!tagsSaved)
			{
				if (errors.Length > l)
					errors.Append(", ");
				errors.Append("Тегов");
			}
			if (!fluidsSaved)
			{
				if (errors.Length > l)
					errors.Append(", ");
				errors.Append("Жидкостей");
			}
			errors.Append(" произошли ошибки");

			if (!itemsSaved || !tagsSaved || !fluidsSaved)
				SaveInfoLabel.Text = errors.ToString();
			else
				SaveInfoLabel.Text = "Определения успешно сохранены";

			ItemsTab.BuildCollection();
			TagsTab.BuildCollection();
			FluidsTab.BuildCollection();
		}

		void OnSaveIntoFileButton_Pressed()
		{
			WhereToSaveDialog.Visible = true;
		}

		void OnWhereToSaveDialog_FileSelected(string path)
		{
			var saveFile = FileAccess.Open(path, FileAccess.ModeFlags.Write);
			if (saveFile == null)
				LogErr(nameof(DeclarationsRedactor), "SaveIntoFile").AddLine($"Error saving the file: {FileAccess.GetOpenError()}").Push();
			
			OnSaveCollectionsButton_Pressed();

			StringBuilder builder = new();

			builder.AppendLine("// It is an autogenerated file and will be rewritten on the next save.\n\n\n");
			builder.AppendLine("// #region Items\n");
			builder.AppendLine(ItemsTab.GetStringView().Replace("item: {", "const item = {"));
			builder.AppendLine("\n// #endregion\n\n\n");

			builder.AppendLine("// #region Tags\n");
			builder.AppendLine(TagsTab.GetStringView().Replace("tag: {", "const tag = {"));
			builder.AppendLine("\n// #endregion\n\n\n");

			builder.AppendLine("// #region Fluids\n");
			builder.AppendLine(FluidsTab.GetStringView().Replace("fluid: {", "const fluid = {"));
			builder.AppendLine("\n// #endregion\n\n\n");

			bool successful = saveFile.StoreString(builder.ToString());

			if (successful)
				LogInfo(nameof(DeclarationsRedactor), "SaveIntoFile").AddLine($"File successfully saved at {path}").Push();
			else
				LogErr(nameof(DeclarationsRedactor), "SaveIntoFile").AddLine($"Error occured saving file, while it was built").Push();

			saveFile.Close();
		}
	}
}